### ISSUE TITLE
Merging isn't Working

### ISSUE THREAD

**Issue by xsudiptaster** [hudec117/sf-user-perm-report#38]
**Describe the bug**
Merging isn't working

build.js:2 Uncaught (in promise) TypeError: Cannot read property 'textContent' of undefined
    at B.merge (build.js:2)
    at i.runReport (build.js:2)
    at chrome-extension://gkibdicghcpcikhjpgjoijpobdipklnp/public/async chrome-extension:/gkibdicghcpcikhjpgjoijpobdipklnp/build.js:2

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a User 
2. Click on the Open permission Report
3. The User has a Custom Profile, standard permission sets and Permission Set Groups. The unique permission Sets are Quip Permission Set provided from Salesforce, Scan to Salesforce permission provided from the app exchange Scan to Salesforce. Pardot Permission Set from the Pardot Lightning App (this is new since this is the new lightning version of Pardot), Analytics Permission Set from Einstein Analytics Platform User with Export. And Tableau CRM Platform User permission set.

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser version [e.g. 88.0.4324.150]
 - Extension version [e.g. 1.0.0]

**Comment by hudec117** [comment]
Thanks for the bug report! Could you please expand on your repro steps? I will need to reproduce the error so I will need information on what permission sets, permission set groups, licenses and profiles to use.

Where the above is custom made, no need to specify the actual name.

**Comment by hudec117** [comment]
@xsudiptaster could you please run:

`SELECT PermissionSet.Name, PermissionSet.Type FROM PermissionSetAssignment WHERE AssigneeId = 'USERID' AND PermissionSet.IsOwnedByProfile = false`

Where "USERID" is the ID of the user you are running the report for. Please censor anything confidential.

**Comment by xsudiptaster** [comment]
PermissionSet.Name PermissionSet.Type
EinsteinAnalyticsUser Regular
ChangeRecordOwner Regular
Messenger_User Regular
Champions Group
GeoRefrenceAdmin Regular
Scan_to_Salesforce Regular
BPO_Change_Requests Regular
Create_Change_Request Regular
EinsteinAnalyticsUser Standard
Quip Regular
Pardot Regular
ManageDashboardsForOthers Regular
Manage_Territories Regular
Export_Reports Regular
Standard_User Group

**Comment by hudec117** [comment]
This could be related to another issue. Could you please try running:

`SELECT PermissionSet.Name, PermissionSet.Type, PermissionSet.IsOwnedByProfile FROM PermissionSetGroupComponent WHERE PermissionSetGroup.DeveloperName IN ('Champions', 'Standard_User ')`

**Comment by hudec117** [comment]
@xsudiptaster have you been able to look at my previous comment?

**Comment by hudec117** [comment]
@raleighing to debug this I'll release a version with error handling in the merge function to get more info on the error.

**Comment by hudec117** [comment]
@raleighing 1.2.2 has been released to the Chrome Web Store and should be downloaded by your browser. Could you please try to replicate this error? Open the console before it happens, you'll see an error log with the metadata that it failed on. Please Right Click -> Copy outerHTML, paste in a file and attach here?

I appreciate it may contain sensitive information so I just need to know what kind of metadata it is and why it does not have a "fullName" element.

**Comment by raleighing** [comment]
Here's what is returned when I right-click on "metadata" in the console error and select "Copy outerHTML":
`<records xmlns="http://soap.sforce.com/2006/04/metadata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>`

**Comment by hudec117** [comment]
@raleighing sorry, what if you selected "Copy element"? It may be very large. I'm looking for what the metadata is (standard permission set? standard profile? guest user? something special? wrongly downloaded metadata?)

**Comment by hudec117** [comment]
I have been able to replicate this issue by putting a managed Permission Set into a permission set group and then trying to run the report. Is this the case in your scenario?

**Comment by hudec117** [comment]
This should be fixed as of 1.2.4, in the process of being published to the Chrome Web Store. If you find it still doesn't work with the update, feel free to re-open!
