### ISSUE TITLE
Buton is not available anymore

### ISSUE THREAD

**Issue by Rick45** [hudec117/sf-user-perm-report#48]
**Describe the bug**
Buton is not available in the user page.

i dont see any error and the extension seems updated. Other persons that also use it have the same behavior

**To Reproduce**
1. Go to any user
2. the button is not available

**Screenshots**
![image](https://github.com/user-attachments/assets/1b68cf82-0e47-4344-99b7-dcddf4a05c6c)

**Desktop (please complete the following information):**
 - Chrome Version 130.0.6723.59 (Official Build) (64-bit)
 - Extension version 1.2.4

**Comment by Rick45** [comment]
extra information, this should be related to the lastes update from salesforce, the button is working in production but on sandboxes is missing

**Comment by hudec117** [comment]
I believe this is due to Salesforce using a new domain for the Setup pages. Will update

**Comment by hudec117** [comment]
@Rick45 fixed in 1.2.5
